import { readFileSync, writeFileSync } from "node:fs";
import { INDEX_PATH, type TaskIndex } from "./_schema.ts";
const idx: TaskIndex = JSON.parse(readFileSync(INDEX_PATH, "utf8"));
const banner = (name: string) => `<!-- GENERATED by scripts/tasks/regenerate-views.ts from _index.json — DO NOT EDIT (${name}) -->\n\n`;
const waves = [...new Set(idx.tasks.map(t => t.wave))].sort((a, b) => a - b);
const mark = (s: string) => ({ todo: "☐", "in-progress": "◐", done: "☑", blocked: "⊘", skipped: "–" } as Record<string, string>)[s] ?? s;
let backlog = banner("_backlog.md") + `# orient — Task backlog\n\n${idx.tasks.length} tasks · generated ${idx.generated}\n\n| Wave | Status | Task | Layer | Effort | Stories | Dependencies |\n|---|---|---|---|---|---|---|\n`;
for (const t of idx.tasks) backlog += `| ${t.wave} | ${mark(t.status)} ${t.status} | [${t.id}](${t.id}.md) — ${t.title} | ${t.layer} | ${t.effort} | ${t.stories.join(", ") || (t.notes ?? "").startsWith("infrastructure") ? (t.stories.join(", ") || "infra") : "—"} | ${t.dependencies.join(", ") || "—"} |\n`;
writeFileSync("akaaso/09-tasks/_backlog.md", backlog);
let wv = banner("_waves.md") + `# orient — Waves\n\nWave N = every impl task whose dependencies all sit in waves 0..N-1. A gate task closes each wave and runs inline on develop.\n\n`;
for (const w of waves) {
  const ts = idx.tasks.filter(t => t.wave === w);
  wv += `## Wave ${w} — ${ts.filter(t => !t.id.startsWith("WAVE")).length} tasks + gate\n\n` + ts.map(t => `- ${mark(t.status)} **${t.id}** — ${t.title} (${t.layer}, ${t.effort})`).join("\n") + "\n\n";
}
writeFileSync("akaaso/09-tasks/_waves.md", wv);
let dg = banner("_dependency-graph.md") + "# orient — Dependency graph\n\n```mermaid\ngraph TD\n";
for (const t of idx.tasks) { if (t.id.startsWith("WAVE")) continue; const n = t.id.replace(/[^A-Za-z0-9]/g, "_"); dg += `  ${n}["${t.id}\\nw${t.wave}"]\n`; for (const d of t.dependencies) if (!d.startsWith("WAVE")) dg += `  ${d.replace(/[^A-Za-z0-9]/g, "_")} --> ${n}\n`; }
dg += "```\n"; writeFileSync("akaaso/09-tasks/_dependency-graph.md", dg);
console.log(`views regenerated for ${idx.tasks.length} tasks, ${waves.length} waves`);
